### ISSUE TITLE
Howto add nunjucks date filter?

### ISSUE THREAD

**Issue by tinkajts** [deligenius/view-engine#14]
Is there a way to add this date filter to the nunjuncks template engine via View-engine?

https://github.com/e-picas/nunjucks-date-filter

Would be really nice with a code example in the Readme.md.

Thank you for your great work on this repo!

**Comment by gjuoun** [comment]
I suspect that it would work with view-engine.
Since view-engine is using [denjucks](https://github.com/denjucks/denjucks). It has a bit of different implementation than `nunjuck`. And `nunjucks data filter` has the dependency of `nunjucks`, I doubt it would compatible with `denjucks`. 

But before that, you may want to ask denjucks author, I'm not an expert on that.
