### ISSUE TITLE
Import error: oak/mod.ts not found

### ISSUE THREAD

**Issue by mikolaj6r** [deligenius/view-engine#6]
Imports should be bound to specific version of module, otherwise there could be some errors like this one.
![ss_error](https://user-images.githubusercontent.com/35143306/84662585-4c2a3100-af1c-11ea-9cc5-baf023ee12bf.PNG)

```bash
3:18:25 PM web.1 |  error: Import 'https://deno.land/x/oak/mod.ts' failed: 404 Not Found
```

**Comment by HaarisIqubal** [comment]
Try importing the module like this if you want specific version

“https://deno.land/x/oak@v3.0.0/mod.ts”

While if you want to import current version

“ https://deno.land/x/oak/mod.ts”

You can test this simply type inside the browser.

**Comment by gjuoun** [comment]
Since ```OakAdapter``` has a type merging for `Oak`'s `Application`,
Type merging enables `View-Engine` to define a `ctx.render` function in Oak, it can only be merging one version at a time.
So that `View-Engine` is designed to be compatible with the newest version of `Oak`.

But thanks for reporting this issue, I will make a new release which sticks to a fixed version of Oak

**Comment by gjuoun** [comment]
Release v1.1.1 https://github.com/deligenius/view-engine/releases/tag/v1.1.1 
bounds to oak@v5.2.0
